In [3]:
import numpy as np
from itertools import product

def mat(n,k):
    A=np.zeros((n,n))

    for i,j,t in product(range(n),range(n),range(k+1)):
        if abs(i-j)==t:
            A[i][j]=1 

    return A

In [4]:
print(mat(6,2))

[[1. 1. 1. 0. 0. 0.]
 [1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1.]]


In [5]:
def avg(n,k):    # creating the average matrix operator
    
    A=mat(n,k)

    for i in range(n):
        r = np.sum(A[i])
        A[i]=A[i]/r

    return A

In [6]:
print(avg(6,2))

[[0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
 [0.25       0.25       0.25       0.25       0.         0.        ]
 [0.2        0.2        0.2        0.2        0.2        0.        ]
 [0.         0.2        0.2        0.2        0.2        0.2       ]
 [0.         0.         0.25       0.25       0.25       0.25      ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333]]


In [11]:
n=20
k=2

x = np.array([(-1)**j for j in range(n)])
x

array([ 1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1, -1,  1,
       -1,  1, -1])

In [12]:
A=avg(n,k)

A@x

array([ 0.33333333,  0.        ,  0.2       , -0.2       ,  0.2       ,
       -0.2       ,  0.2       , -0.2       ,  0.2       , -0.2       ,
        0.2       , -0.2       ,  0.2       , -0.2       ,  0.2       ,
       -0.2       ,  0.2       , -0.2       ,  0.        , -0.33333333])

In [9]:
def f(x):
    return x**2 + 2*np.sin(10*x)

In [10]:
n=1000
k=100

x = np.linspace(0, 10, n)

avg(n,k)@f(x)

array([ 0.69262169,  0.68344189,  0.67319704,  0.66205593,  0.65019371,
        0.63779016,  0.62502789,  0.61209053,  0.59916104,  0.58641998,
        0.57404378,  0.56220322,  0.55106188,  0.54077469,  0.53148662,
        0.52333145,  0.51643073,  0.51089274,  0.50681174,  0.50426728,
        0.50332365,  0.50402953,  0.50641773,  0.51050519,  0.51629298,
        0.52376657,  0.53289621,  0.54363742,  0.55593164,  0.569707  ,
        0.5848792 ,  0.60135248,  0.61902073,  0.63776864,  0.65747292,
        0.67800364,  0.69922552,  0.72099933,  0.74318325,  0.76563433,
        0.78820982,  0.81076856,  0.83317232,  0.85528707,  0.87698425,
        0.89814191,  0.91864578,  0.93839031,  0.95727954,  0.97522793,
        0.99216101,  1.00801599,  1.0227422 ,  1.03630141,  1.04866809,
        1.05982942,  1.06978533,  1.07854829,  1.08614304,  1.0926062 ,
        1.09798579,  1.10234059,  1.10573944,  1.10826047,  1.10999021,
        1.11102265,  1.11145824,  1.11140283,  1.11096658,  1.11