In [90]:
def swaprow(i, j, A):
    tmp = A[i, :]
    A[i, :] = A[j, :]
    A[j, :] = tmp

In [91]:
import numpy as np

A=np.random.randint(0,10,size=(3,3))        # Creating a random matrix
print(A)

[[3 4 1]
 [5 4 6]
 [3 1 2]]


In [92]:
swaprow(1,2,A)
print(A)

[[3 4 1]
 [3 1 2]
 [3 1 2]]


The method is not correct. Because in python indexing starts from 0. Also tmp is not deep copying the array, it pointing the same object. We have to adjust little bit and add copy().

In [93]:
def swaprow(i, j, A):
    i-=1        # correcting the index
    j-=1

    tmp = A[i, :].copy()    # deep copying
    A[i, :] = A[j, :]
    A[j, :] = tmp

In [94]:
import numpy as np

A=np.random.randint(0,10,size=(3,3))        # Creating a random matrix
print(A)

[[4 8 1]
 [3 3 5]
 [4 8 7]]


In [95]:
swaprow(2,3,A)
print(A)

[[4 8 1]
 [4 8 7]
 [3 3 5]]


But this is creating unnecessary copies. It is not efficient.

In [96]:
# Better function for swapping rows

def swap_rows(i,j,A):
    i-=1 ; j-=1  # correcting to usual indexing

    A[[i,j]]=A[[j,i]]   # swaping rows

In [97]:
import numpy as np

A=np.random.randint(0,10,size=(3,3))        # Creating a random matrix
print(A)

[[7 6 9]
 [6 1 5]
 [8 5 7]]


In [98]:
swap_rows(2,3,A)
print(A)

[[7 6 9]
 [8 5 7]
 [6 1 5]]


This swaps the $i^{th}$ and $j^{th}$ rows using numpy built in feature. Which is more efficient and it does not need to deep copy.