In [1]:
import numpy as np
from scipy.linalg import svd, qr

A = np.array([[1, -2, 3, -3], [2, -4, 9, -2], [-3, 6, -9, 9]])

In [2]:
# Column space of A using QR

Q, R = qr(A)
column_space_basis_qr = Q       # The columns of Q form a basis for the column space
print(column_space_basis_qr)    

[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]


In [3]:
# Column space of A using SVD

U, S, Vt = svd(A)
column_space_basis_svd = U      # The columns of U form a basis for the column space
print(column_space_basis_svd)

[[-2.66235859e-01 -1.70641342e-01  9.48683298e-01]
 [-5.39615303e-01  8.41911709e-01 -5.55111512e-17]
 [ 7.98707576e-01  5.11924025e-01  3.16227766e-01]]


In [4]:
# To check if two bases span the same space, we can compare their dimensions.
# If the dimensions are the same, they span the same space as they are subset of column space.

if column_space_basis_qr.shape[1] == column_space_basis_svd.shape[1]:
    print("Column spaces obtained using QR and SVD are the same.")
else:
    print("Column spaces obtained using QR and SVD are not the same.")

Column spaces obtained using QR and SVD are the same.


In [5]:
import time

random_matrix = np.random.rand(500, 500)

# Measure the time taken for QR decomposition
start_time_qr = time.time()
Q, R = qr(random_matrix)
qr_time = time.time() - start_time_qr

# Measure the time taken for SVD
start_time_svd = time.time()
U, S, Vt = svd(random_matrix)
svd_time = time.time() - start_time_svd

if qr_time < svd_time:
    print(f"QR decomposition is faster for a 500x500 random matrix. QR time={qr_time:.5f}s and SVD time={svd_time:.5f}s")
else:
    print("SVD is faster for a 500x500 random matrix. QR time={qr_time:.5f}s and SVD time={svd_time:.5f}s")

QR decomposition is faster for a 500x500 random matrix. QR time=0.01001s and SVD time=0.03399s
